import tkinter as tk


class ExamModify:
    def __init__(self, top=None):
        top.geometry("327x602+562+80")
        top.minsize(120, 1)
        top.maxsize(1370, 749)
        top.resizable(0,0)
        top.title("Modify")
        top.configure(background="#CED4DA")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")

        self.present_label = tk.Label(top)
        self.present_label.place(relx=0.245, rely=0.017, height=19, width=154)
        self.present_label.configure(activebackground="#CED4DA")
        self.present_label.configure(activeforeground="black")
        self.present_label.configure(background="#CED4DA")
        self.present_label.configure(disabledforeground="#a3a3a3")
        self.present_label.configure(font="-family {Segoe UI} -size 13 -weight bold")
        self.present_label.configure(foreground="#212529")
        self.present_label.configure(highlightbackground="#d9d9d9")
        self.present_label.configure(highlightcolor="black")
        self.present_label.configure(text='''PRESENT DATA''')

        self.new_label = tk.Label(top)
        self.new_label.place(relx=0.306, rely=0.473, height=19, width=114)
        self.new_label.configure(activebackground="#f9f9f9")
        self.new_label.configure(activeforeground="black")
        self.new_label.configure(background="#CED4DA")
        self.new_label.configure(disabledforeground="#a3a3a3")
        self.new_label.configure(font="-family {Segoe UI} -size 13 -weight bold")
        self.new_label.configure(foreground="#212529")
        self.new_label.configure(highlightbackground="#d9d9d9")
        self.new_label.configure(highlightcolor="black")
        self.new_label.configure(text='''NEW DATA''')

        self.exam_label1 = tk.Label(top)
        self.exam_label1.place(relx=0.245, rely=0.066, height=19, width=55)
        self.exam_label1.configure(activebackground="#f9f9f9")
        self.exam_label1.configure(activeforeground="black")
        self.exam_label1.configure(background="#CED4DA")
        self.exam_label1.configure(disabledforeground="#a3a3a3")
        self.exam_label1.configure(foreground="#000000")
        self.exam_label1.configure(highlightbackground="#d9d9d9")
        self.exam_label1.configure(highlightcolor="black")
        self.exam_label1.configure(text='''Exam id :''')

        self.exam_entry1 = tk.Entry(top)
        self.exam_entry1.place(relx=0.459, rely=0.066, height=20, relwidth=0.318)
        self.exam_entry1.configure(background="white")
        self.exam_entry1.configure(disabledforeground="#a3a3a3")
        self.exam_entry1.configure(font="TkFixedFont")
        self.exam_entry1.configure(foreground="#000000")
        self.exam_entry1.configure(highlightbackground="#d9d9d9")
        self.exam_entry1.configure(highlightcolor="black")
        self.exam_entry1.configure(insertbackground="black")
        self.exam_entry1.configure(selectbackground="blue")
        self.exam_entry1.configure(selectforeground="white")

        self.name_label1 = tk.Label(top)
        self.name_label1.place(relx=0.275, rely=0.116, height=18, width=46)
        self.name_label1.configure(activebackground="#f9f9f9")
        self.name_label1.configure(activeforeground="black")
        self.name_label1.configure(background="#CED4DA")
        self.name_label1.configure(disabledforeground="#a3a3a3")
        self.name_label1.configure(foreground="#000000")
        self.name_label1.configure(highlightbackground="#d9d9d9")
        self.name_label1.configure(highlightcolor="black")
        self.name_label1.configure(text='''Name :''')

        self.name_entry1 = tk.Entry(top)
        self.name_entry1.place(relx=0.459, rely=0.116, height=20, relwidth=0.318)
        self.name_entry1.configure(background="white")
        self.name_entry1.configure(disabledforeground="#a3a3a3")
        self.name_entry1.configure(font="TkFixedFont")
        self.name_entry1.configure(foreground="#000000")
        self.name_entry1.configure(highlightbackground="#d9d9d9")
        self.name_entry1.configure(highlightcolor="black")
        self.name_entry1.configure(insertbackground="black")
        self.name_entry1.configure(selectbackground="blue")
        self.name_entry1.configure(selectforeground="white")

        self.duration_label1 = tk.Label(top)
        self.duration_label1.place(relx=0.239, rely=0.166, height=18, width=55)
        self.duration_label1.configure(activebackground="#f9f9f9")
        self.duration_label1.configure(activeforeground="black")
        self.duration_label1.configure(background="#CED4DA")
        self.duration_label1.configure(disabledforeground="#a3a3a3")
        self.duration_label1.configure(foreground="#000000")
        self.duration_label1.configure(highlightbackground="#d9d9d9")
        self.duration_label1.configure(highlightcolor="black")
        self.duration_label1.configure(text='''Duration :''')

        self.duration_entry1 = tk.Entry(top)
        self.duration_entry1.place(relx=0.459, rely=0.166, height=20, relwidth=0.318)
        self.duration_entry1.configure(background="white")
        self.duration_entry1.configure(disabledforeground="#a3a3a3")
        self.duration_entry1.configure(font="TkFixedFont")
        self.duration_entry1.configure(foreground="#000000")
        self.duration_entry1.configure(highlightbackground="#d9d9d9")
        self.duration_entry1.configure(highlightcolor="black")
        self.duration_entry1.configure(insertbackground="black")
        self.duration_entry1.configure(selectbackground="blue")
        self.duration_entry1.configure(selectforeground="white")

        self.date_label1 = tk.Label(top)
        self.date_label1.place(relx=0.275, rely=0.216, height=18, width=55)
        self.date_label1.configure(activebackground="#f9f9f9")
        self.date_label1.configure(activeforeground="black")
        self.date_label1.configure(background="#CED4DA")
        self.date_label1.configure(disabledforeground="#a3a3a3")
        self.date_label1.configure(foreground="#000000")
        self.date_label1.configure(highlightbackground="#d9d9d9")
        self.date_label1.configure(highlightcolor="black")
        self.date_label1.configure(text='''Date :''')

        self.date_entry1 = tk.Entry(top)
        self.date_entry1.place(relx=0.459, rely=0.216, height=20, relwidth=0.318)
        self.date_entry1.configure(background="white")
        self.date_entry1.configure(disabledforeground="#a3a3a3")
        self.date_entry1.configure(font="TkFixedFont")
        self.date_entry1.configure(foreground="#000000")
        self.date_entry1.configure(highlightbackground="#d9d9d9")
        self.date_entry1.configure(highlightcolor="black")
        self.date_entry1.configure(insertbackground="black")
        self.date_entry1.configure(selectbackground="blue")
        self.date_entry1.configure(selectforeground="white")

        self.ques_label1 = tk.Label(top)
        self.ques_label1.place(relx=0.135, rely=0.266, height=18, width=89)
        self.ques_label1.configure(activebackground="#f9f9f9")
        self.ques_label1.configure(activeforeground="black")
        self.ques_label1.configure(background="#CED4DA")
        self.ques_label1.configure(disabledforeground="#a3a3a3")
        self.ques_label1.configure(foreground="#000000")
        self.ques_label1.configure(highlightbackground="#d9d9d9")
        self.ques_label1.configure(highlightcolor="black")
        self.ques_label1.configure(text='''Total questions :''')

        self.ques_entry1 = tk.Entry(top)
        self.ques_entry1.place(relx=0.459, rely=0.266, height=20, relwidth=0.318)
        self.ques_entry1.configure(background="white")
        self.ques_entry1.configure(disabledforeground="#a3a3a3")
        self.ques_entry1.configure(font="TkFixedFont")
        self.ques_entry1.configure(foreground="#000000")
        self.ques_entry1.configure(highlightbackground="#d9d9d9")
        self.ques_entry1.configure(highlightcolor="black")
        self.ques_entry1.configure(insertbackground="black")
        self.ques_entry1.configure(selectbackground="blue")
        self.ques_entry1.configure(selectforeground="white")

        self.marks_label1 = tk.Label(top)
        self.marks_label1.place(relx=0.19, rely=0.316, height=17, width=75)
        self.marks_label1.configure(activebackground="#f9f9f9")
        self.marks_label1.configure(activeforeground="black")
        self.marks_label1.configure(background="#CED4DA")
        self.marks_label1.configure(disabledforeground="#a3a3a3")
        self.marks_label1.configure(foreground="#000000")
        self.marks_label1.configure(highlightbackground="#d9d9d9")
        self.marks_label1.configure(highlightcolor="black")
        self.marks_label1.configure(text='''Total marks :''')

        self.marks_entry1 = tk.Entry(top)
        self.marks_entry1.place(relx=0.459, rely=0.316, height=20, relwidth=0.318)
        self.marks_entry1.configure(background="white")
        self.marks_entry1.configure(disabledforeground="#a3a3a3")
        self.marks_entry1.configure(font="TkFixedFont")
        self.marks_entry1.configure(foreground="#000000")
        self.marks_entry1.configure(highlightbackground="#d9d9d9")
        self.marks_entry1.configure(highlightcolor="black")
        self.marks_entry1.configure(insertbackground="black")
        self.marks_entry1.configure(selectbackground="blue")
        self.marks_entry1.configure(selectforeground="white")

        self.branch_label1 = tk.Label(top)
        self.branch_label1.place(relx=0.22, rely=0.365, height=18, width=64)
        self.branch_label1.configure(activebackground="#f9f9f9")
        self.branch_label1.configure(activeforeground="black")
        self.branch_label1.configure(background="#CED4DA")
        self.branch_label1.configure(disabledforeground="#a3a3a3")
        self.branch_label1.configure(foreground="#000000")
        self.branch_label1.configure(highlightbackground="#d9d9d9")
        self.branch_label1.configure(highlightcolor="black")
        self.branch_label1.configure(text='''Branch id :''')

        self.branch_entry1 = tk.Entry(top)
        self.branch_entry1.place(relx=0.459, rely=0.365, height=20, relwidth=0.318)
        self.branch_entry1.configure(background="white")
        self.branch_entry1.configure(disabledforeground="#a3a3a3")
        self.branch_entry1.configure(font="TkFixedFont")
        self.branch_entry1.configure(foreground="#000000")
        self.branch_entry1.configure(highlightbackground="#d9d9d9")
        self.branch_entry1.configure(highlightcolor="black")
        self.branch_entry1.configure(insertbackground="black")
        self.branch_entry1.configure(selectbackground="blue")
        self.branch_entry1.configure(selectforeground="white")

        self.subject_label1 = tk.Label(top)
        self.subject_label1.place(relx=0.153, rely=0.415, height=18, width=80)
        self.subject_label1.configure(activebackground="#f9f9f9")
        self.subject_label1.configure(activeforeground="black")
        self.subject_label1.configure(background="#CED4DA")
        self.subject_label1.configure(disabledforeground="#a3a3a3")
        self.subject_label1.configure(foreground="#000000")
        self.subject_label1.configure(highlightbackground="#d9d9d9")
        self.subject_label1.configure(highlightcolor="black")
        self.subject_label1.configure(text='''Subject code :''')

        self.subject_entry1 = tk.Entry(top)
        self.subject_entry1.place(relx=0.459, rely=0.415, height=20, relwidth=0.318)
        self.subject_entry1.configure(background="white")
        self.subject_entry1.configure(disabledforeground="#a3a3a3")
        self.subject_entry1.configure(font="TkFixedFont")
        self.subject_entry1.configure(foreground="#000000")
        self.subject_entry1.configure(highlightbackground="#d9d9d9")
        self.subject_entry1.configure(highlightcolor="black")
        self.subject_entry1.configure(insertbackground="black")
        self.subject_entry1.configure(selectbackground="blue")
        self.subject_entry1.configure(selectforeground="white")

        self.exam_label2 = tk.Label(top)
        self.exam_label2.place(relx=0.245, rely=0.523, height=20, width=55)
        self.exam_label2.configure(activebackground="#f9f9f9")
        self.exam_label2.configure(activeforeground="black")
        self.exam_label2.configure(background="#CED4DA")
        self.exam_label2.configure(disabledforeground="#a3a3a3")
        self.exam_label2.configure(foreground="#000000")
        self.exam_label2.configure(highlightbackground="#d9d9d9")
        self.exam_label2.configure(highlightcolor="black")
        self.exam_label2.configure(text='''Exam id :''')

        self.exam_entry2 = tk.Entry(top)
        self.exam_entry2.place(relx=0.459, rely=0.523, height=20, relwidth=0.318)
        self.exam_entry2.configure(background="white")
        self.exam_entry2.configure(disabledforeground="#a3a3a3")
        self.exam_entry2.configure(font="TkFixedFont")
        self.exam_entry2.configure(foreground="#000000")
        self.exam_entry2.configure(highlightbackground="#d9d9d9")
        self.exam_entry2.configure(highlightcolor="black")
        self.exam_entry2.configure(insertbackground="black")
        self.exam_entry2.configure(selectbackground="blue")
        self.exam_entry2.configure(selectforeground="white")

        self.name_label2 = tk.Label(top)
        self.name_label2.place(relx=0.275, rely=0.573, height=18, width=46)
        self.name_label2.configure(activebackground="#f9f9f9")
        self.name_label2.configure(activeforeground="black")
        self.name_label2.configure(background="#CED4DA")
        self.name_label2.configure(disabledforeground="#a3a3a3")
        self.name_label2.configure(foreground="#000000")
        self.name_label2.configure(highlightbackground="#d9d9d9")
        self.name_label2.configure(highlightcolor="black")
        self.name_label2.configure(text='''Name :''')

        self.name_entry2 = tk.Entry(top)
        self.name_entry2.place(relx=0.459, rely=0.573, height=20, relwidth=0.318)
        self.name_entry2.configure(background="white")
        self.name_entry2.configure(disabledforeground="#a3a3a3")
        self.name_entry2.configure(font="TkFixedFont")
        self.name_entry2.configure(foreground="#000000")
        self.name_entry2.configure(highlightbackground="#d9d9d9")
        self.name_entry2.configure(highlightcolor="black")
        self.name_entry2.configure(insertbackground="black")
        self.name_entry2.configure(selectbackground="blue")
        self.name_entry2.configure(selectforeground="white")

        self.duration_label2 = tk.Label(top)
        self.duration_label2.place(relx=0.239, rely=0.623, height=18, width=55)
        self.duration_label2.configure(activebackground="#f9f9f9")
        self.duration_label2.configure(activeforeground="black")
        self.duration_label2.configure(background="#CED4DA")
        self.duration_label2.configure(disabledforeground="#a3a3a3")
        self.duration_label2.configure(foreground="#000000")
        self.duration_label2.configure(highlightbackground="#d9d9d9")
        self.duration_label2.configure(highlightcolor="black")
        self.duration_label2.configure(text='''Duration :''')

        self.duration_entry2 = tk.Entry(top)
        self.duration_entry2.place(relx=0.459, rely=0.623, height=20, relwidth=0.318)
        self.duration_entry2.configure(background="white")
        self.duration_entry2.configure(disabledforeground="#a3a3a3")
        self.duration_entry2.configure(font="TkFixedFont")
        self.duration_entry2.configure(foreground="#000000")
        self.duration_entry2.configure(highlightbackground="#d9d9d9")
        self.duration_entry2.configure(highlightcolor="black")
        self.duration_entry2.configure(insertbackground="black")
        self.duration_entry2.configure(selectbackground="blue")
        self.duration_entry2.configure(selectforeground="white")

        self.date_label2 = tk.Label(top)
        self.date_label2.place(relx=0.275, rely=0.673, height=18, width=55)
        self.date_label2.configure(activebackground="#f9f9f9")
        self.date_label2.configure(activeforeground="black")
        self.date_label2.configure(background="#CED4DA")
        self.date_label2.configure(disabledforeground="#a3a3a3")
        self.date_label2.configure(foreground="#000000")
        self.date_label2.configure(highlightbackground="#d9d9d9")
        self.date_label2.configure(highlightcolor="black")
        self.date_label2.configure(text='''Date :''')

        self.date_entry2 = tk.Entry(top)
        self.date_entry2.place(relx=0.459, rely=0.673, height=20, relwidth=0.318)
        self.date_entry2.configure(background="white")
        self.date_entry2.configure(disabledforeground="#a3a3a3")
        self.date_entry2.configure(font="TkFixedFont")
        self.date_entry2.configure(foreground="#000000")
        self.date_entry2.configure(highlightbackground="#d9d9d9")
        self.date_entry2.configure(highlightcolor="black")
        self.date_entry2.configure(insertbackground="black")
        self.date_entry2.configure(selectbackground="blue")
        self.date_entry2.configure(selectforeground="white")

        self.ques_label2 = tk.Label(top)
        self.ques_label2.place(relx=0.135, rely=0.723, height=18, width=89)
        self.ques_label2.configure(activebackground="#f9f9f9")
        self.ques_label2.configure(activeforeground="black")
        self.ques_label2.configure(background="#CED4DA")
        self.ques_label2.configure(disabledforeground="#a3a3a3")
        self.ques_label2.configure(foreground="#000000")
        self.ques_label2.configure(highlightbackground="#d9d9d9")
        self.ques_label2.configure(highlightcolor="black")
        self.ques_label2.configure(text='''Total questions:''')

        self.ques_entry2 = tk.Entry(top)
        self.ques_entry2.place(relx=0.459, rely=0.723, height=20, relwidth=0.318)
        self.ques_entry2.configure(background="white")
        self.ques_entry2.configure(disabledforeground="#a3a3a3")
        self.ques_entry2.configure(font="TkFixedFont")
        self.ques_entry2.configure(foreground="#000000")
        self.ques_entry2.configure(highlightbackground="#d9d9d9")
        self.ques_entry2.configure(highlightcolor="black")
        self.ques_entry2.configure(insertbackground="black")
        self.ques_entry2.configure(selectbackground="blue")
        self.ques_entry2.configure(selectforeground="white")

        self.marks_label2 = tk.Label(top)
        self.marks_label2.place(relx=0.19, rely=0.772, height=17, width=75)
        self.marks_label2.configure(activebackground="#f9f9f9")
        self.marks_label2.configure(activeforeground="black")
        self.marks_label2.configure(background="#CED4DA")
        self.marks_label2.configure(disabledforeground="#a3a3a3")
        self.marks_label2.configure(foreground="#000000")
        self.marks_label2.configure(highlightbackground="#d9d9d9")
        self.marks_label2.configure(highlightcolor="black")
        self.marks_label2.configure(text='''Total marks:''')

        self.marks_entry2 = tk.Entry(top)
        self.marks_entry2.place(relx=0.459, rely=0.772, height=20, relwidth=0.318)
        self.marks_entry2.configure(background="white")
        self.marks_entry2.configure(disabledforeground="#a3a3a3")
        self.marks_entry2.configure(font="TkFixedFont")
        self.marks_entry2.configure(foreground="#000000")
        self.marks_entry2.configure(highlightbackground="#d9d9d9")
        self.marks_entry2.configure(highlightcolor="black")
        self.marks_entry2.configure(insertbackground="black")
        self.marks_entry2.configure(selectbackground="blue")
        self.marks_entry2.configure(selectforeground="white")

        self.branch_label2 = tk.Label(top)
        self.branch_label2.place(relx=0.22, rely=0.822, height=18, width=64)
        self.branch_label2.configure(activebackground="#f9f9f9")
        self.branch_label2.configure(activeforeground="black")
        self.branch_label2.configure(background="#CED4DA")
        self.branch_label2.configure(disabledforeground="#a3a3a3")
        self.branch_label2.configure(foreground="#000000")
        self.branch_label2.configure(highlightbackground="#d9d9d9")
        self.branch_label2.configure(highlightcolor="black")
        self.branch_label2.configure(text='''Branch id:''')

        self.branch_entry2 = tk.Entry(top)
        self.branch_entry2.place(relx=0.459, rely=0.822, height=20, relwidth=0.318)
        self.branch_entry2.configure(background="white")
        self.branch_entry2.configure(disabledforeground="#a3a3a3")
        self.branch_entry2.configure(font="TkFixedFont")
        self.branch_entry2.configure(foreground="#000000")
        self.branch_entry2.configure(highlightbackground="#d9d9d9")
        self.branch_entry2.configure(highlightcolor="black")
        self.branch_entry2.configure(insertbackground="black")
        self.branch_entry2.configure(selectbackground="blue")
        self.branch_entry2.configure(selectforeground="white")

        self.subject_label2 = tk.Label(top)
        self.subject_label2.place(relx=0.168, rely=0.872, height=18, width=80)
        self.subject_label2.configure(activebackground="#f9f9f9")
        self.subject_label2.configure(activeforeground="black")
        self.subject_label2.configure(background="#CED4DA")
        self.subject_label2.configure(disabledforeground="#a3a3a3")
        self.subject_label2.configure(foreground="#000000")
        self.subject_label2.configure(highlightbackground="#d9d9d9")
        self.subject_label2.configure(highlightcolor="black")
        self.subject_label2.configure(text='''Subject code:''')

        self.subject_entry2 = tk.Entry(top)
        self.subject_entry2.place(relx=0.459, rely=0.872, height=20, relwidth=0.318)
        self.subject_entry2.configure(background="white")
        self.subject_entry2.configure(disabledforeground="#a3a3a3")
        self.subject_entry2.configure(font="TkFixedFont")
        self.subject_entry2.configure(foreground="#000000")
        self.subject_entry2.configure(highlightbackground="#d9d9d9")
        self.subject_entry2.configure(highlightcolor="black")
        self.subject_entry2.configure(insertbackground="black")
        self.subject_entry2.configure(selectbackground="blue")
        self.subject_entry2.configure(selectforeground="white")

        self.modify_button = tk.Button(top)
        self.modify_button.place(relx=0.642, rely=0.93, height=24, width=77)
        self.modify_button.configure(activebackground="#ececec")
        self.modify_button.configure(activeforeground="#000000")
        self.modify_button.configure(background="#E9ECEF")
        self.modify_button.configure(disabledforeground="#a3a3a3")
        self.modify_button.configure(foreground="#000000")
        self.modify_button.configure(highlightbackground="#d9d9d9")
        self.modify_button.configure(highlightcolor="black")
        self.modify_button.configure(pady="0")
        self.modify_button.configure(text='''Modify''')

        self.cancel_button = tk.Button(top)
        self.cancel_button.place(relx=0.183, rely=0.93, height=24, width=77)
        self.cancel_button.configure(activebackground="#ececec")
        self.cancel_button.configure(activeforeground="#000000")
        self.cancel_button.configure(background="#E9ECEF")
        self.cancel_button.configure(disabledforeground="#a3a3a3")
        self.cancel_button.configure(foreground="#000000")
        self.cancel_button.configure(highlightbackground="#d9d9d9")
        self.cancel_button.configure(highlightcolor="black")
        self.cancel_button.configure(pady="0")
        self.cancel_button.configure(text='''Cancel''')


root = tk.Tk()
top = ExamModify(root)
root.mainloop()