import tkinter as tk


class ExamAdd:
    def __init__(self, top=None):
        top.geometry("342x316+624+174")
        top.minsize(120, 1)
        top.maxsize(1370, 749)
        top.resizable(1,  1)
        top.title("Add")
        top.configure(background="#CED4DA")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")

        self.exam_id_label = tk.Label(top)
        self.exam_id_label.place(relx=0.234, rely=0.063, height=21, width=64)
        self.exam_id_label.configure(activebackground="#f9f9f9")
        self.exam_id_label.configure(activeforeground="black")
        self.exam_id_label.configure(background="#CED4DA")
        self.exam_id_label.configure(disabledforeground="#a3a3a3")
        self.exam_id_label.configure(foreground="#000000")
        self.exam_id_label.configure(highlightbackground="#d9d9d9")
        self.exam_id_label.configure(highlightcolor="black")
        self.exam_id_label.configure(text='''Exam id :''')

        self.exam_duration_label = tk.Label(top)
        self.exam_duration_label.place(relx=0.14, rely=0.253, height=18
                , width=94)
        self.exam_duration_label.configure(activebackground="#f9f9f9")
        self.exam_duration_label.configure(activeforeground="black")
        self.exam_duration_label.configure(background="#CED4DA")
        self.exam_duration_label.configure(disabledforeground="#a3a3a3")
        self.exam_duration_label.configure(foreground="#000000")
        self.exam_duration_label.configure(highlightbackground="#d9d9d9")
        self.exam_duration_label.configure(highlightcolor="black")
        self.exam_duration_label.configure(text='''Exam duration :''')

        self.exam_id_entry = tk.Entry(top)
        self.exam_id_entry.place(relx=0.468, rely=0.063, height=20
                , relwidth=0.304)
        self.exam_id_entry.configure(background="white")
        self.exam_id_entry.configure(disabledforeground="#a3a3a3")
        self.exam_id_entry.configure(font="TkFixedFont")
        self.exam_id_entry.configure(foreground="#000000")
        self.exam_id_entry.configure(highlightbackground="#d9d9d9")
        self.exam_id_entry.configure(highlightcolor="black")
        self.exam_id_entry.configure(insertbackground="black")
        self.exam_id_entry.configure(selectbackground="blue")
        self.exam_id_entry.configure(selectforeground="white")

        self.name_entry = tk.Entry(top)
        self.name_entry.place(relx=0.468, rely=0.158, height=20, relwidth=0.304)
        self.name_entry.configure(background="white")
        self.name_entry.configure(disabledforeground="#a3a3a3")
        self.name_entry.configure(font="TkFixedFont")
        self.name_entry.configure(foreground="#000000")
        self.name_entry.configure(highlightbackground="#d9d9d9")
        self.name_entry.configure(highlightcolor="black")
        self.name_entry.configure(insertbackground="black")
        self.name_entry.configure(selectbackground="blue")
        self.name_entry.configure(selectforeground="white")

        self.back_button = tk.Button(top)
        self.back_button.place(relx=0.175, rely=0.854, height=24, width=87)
        self.back_button.configure(activebackground="#ececec")
        self.back_button.configure(activeforeground="#000000")
        self.back_button.configure(background="#E9ECEF")
        self.back_button.configure(disabledforeground="#a3a3a3")
        self.back_button.configure(foreground="#000000")
        self.back_button.configure(highlightbackground="#d9d9d9")
        self.back_button.configure(highlightcolor="black")
        self.back_button.configure(pady="0")
        self.back_button.configure(text='''Back''')

        self.add_button = tk.Button(top)
        self.add_button.place(relx=0.585, rely=0.854, height=24, width=87)
        self.add_button.configure(activebackground="#ececec")
        self.add_button.configure(activeforeground="#000000")
        self.add_button.configure(background="#E9ECEF")
        self.add_button.configure(disabledforeground="#a3a3a3")
        self.add_button.configure(foreground="#000000")
        self.add_button.configure(highlightbackground="#d9d9d9")
        self.add_button.configure(highlightcolor="black")
        self.add_button.configure(pady="0")
        self.add_button.configure(text='''Add''')

        self.tot_ques_label = tk.Label(top)
        self.tot_ques_label.place(relx=0.117, rely=0.443, height=18, width=104)
        self.tot_ques_label.configure(activebackground="#f9f9f9")
        self.tot_ques_label.configure(activeforeground="black")
        self.tot_ques_label.configure(background="#CED4DA")
        self.tot_ques_label.configure(disabledforeground="#a3a3a3")
        self.tot_ques_label.configure(foreground="#000000")
        self.tot_ques_label.configure(highlightbackground="#d9d9d9")
        self.tot_ques_label.configure(highlightcolor="black")
        self.tot_ques_label.configure(text='''Total questions :''')

        self.branch_id_label = tk.Label(top)
        self.branch_id_label.place(relx=0.205, rely=0.633, height=18, width=74)
        self.branch_id_label.configure(activebackground="#f9f9f9")
        self.branch_id_label.configure(activeforeground="black")
        self.branch_id_label.configure(background="#CED4DA")
        self.branch_id_label.configure(disabledforeground="#a3a3a3")
        self.branch_id_label.configure(foreground="#000000")
        self.branch_id_label.configure(highlightbackground="#d9d9d9")
        self.branch_id_label.configure(highlightcolor="black")
        self.branch_id_label.configure(text='''Branch id :''')

        self.duration_entry = tk.Entry(top)
        self.duration_entry.place(relx=0.468, rely=0.253, height=20
                , relwidth=0.304)
        self.duration_entry.configure(background="white")
        self.duration_entry.configure(disabledforeground="#a3a3a3")
        self.duration_entry.configure(font="TkFixedFont")
        self.duration_entry.configure(foreground="#000000")
        self.duration_entry.configure(highlightbackground="#d9d9d9")
        self.duration_entry.configure(highlightcolor="black")
        self.duration_entry.configure(insertbackground="black")
        self.duration_entry.configure(selectbackground="blue")
        self.duration_entry.configure(selectforeground="white")

        self.date_entry = tk.Entry(top)
        self.date_entry.place(relx=0.468, rely=0.348, height=20, relwidth=0.304)
        self.date_entry.configure(background="white")
        self.date_entry.configure(disabledforeground="#a3a3a3")
        self.date_entry.configure(font="TkFixedFont")
        self.date_entry.configure(foreground="#000000")
        self.date_entry.configure(highlightbackground="#d9d9d9")
        self.date_entry.configure(highlightcolor="black")
        self.date_entry.configure(insertbackground="black")
        self.date_entry.configure(selectbackground="blue")
        self.date_entry.configure(selectforeground="white")

        self.tot_ques_entry = tk.Entry(top)
        self.tot_ques_entry.place(relx=0.468, rely=0.443, height=20
                , relwidth=0.304)
        self.tot_ques_entry.configure(background="white")
        self.tot_ques_entry.configure(disabledforeground="#a3a3a3")
        self.tot_ques_entry.configure(font="TkFixedFont")
        self.tot_ques_entry.configure(foreground="#000000")
        self.tot_ques_entry.configure(highlightbackground="#d9d9d9")
        self.tot_ques_entry.configure(highlightcolor="black")
        self.tot_ques_entry.configure(insertbackground="black")
        self.tot_ques_entry.configure(selectbackground="blue")
        self.tot_ques_entry.configure(selectforeground="white")

        self.tot_marks_entry = tk.Entry(top)
        self.tot_marks_entry.place(relx=0.468, rely=0.538, height=20
                , relwidth=0.304)
        self.tot_marks_entry.configure(background="white")
        self.tot_marks_entry.configure(disabledforeground="#a3a3a3")
        self.tot_marks_entry.configure(font="TkFixedFont")
        self.tot_marks_entry.configure(foreground="#000000")
        self.tot_marks_entry.configure(highlightbackground="#d9d9d9")
        self.tot_marks_entry.configure(highlightcolor="black")
        self.tot_marks_entry.configure(insertbackground="black")
        self.tot_marks_entry.configure(selectbackground="blue")
        self.tot_marks_entry.configure(selectforeground="white")

        self.branch_id_entry = tk.Entry(top)
        self.branch_id_entry.place(relx=0.468, rely=0.633, height=20
                , relwidth=0.304)
        self.branch_id_entry.configure(background="white")
        self.branch_id_entry.configure(disabledforeground="#a3a3a3")
        self.branch_id_entry.configure(font="TkFixedFont")
        self.branch_id_entry.configure(foreground="#000000")
        self.branch_id_entry.configure(highlightbackground="#d9d9d9")
        self.branch_id_entry.configure(highlightcolor="black")
        self.branch_id_entry.configure(insertbackground="black")
        self.branch_id_entry.configure(selectbackground="blue")
        self.branch_id_entry.configure(selectforeground="white")

        self.sub_code_entry = tk.Entry(top)
        self.sub_code_entry.place(relx=0.468, rely=0.728, height=20
                , relwidth=0.304)
        self.sub_code_entry.configure(background="white")
        self.sub_code_entry.configure(disabledforeground="#a3a3a3")
        self.sub_code_entry.configure(font="TkFixedFont")
        self.sub_code_entry.configure(foreground="#000000")
        self.sub_code_entry.configure(highlightbackground="#d9d9d9")
        self.sub_code_entry.configure(highlightcolor="black")
        self.sub_code_entry.configure(insertbackground="black")
        self.sub_code_entry.configure(selectbackground="blue")
        self.sub_code_entry.configure(selectforeground="white")

        self.exam_name_label = tk.Label(top)
        self.exam_name_label.place(relx=0.175, rely=0.158, height=21, width=84)
        self.exam_name_label.configure(activebackground="#f9f9f9")
        self.exam_name_label.configure(activeforeground="black")
        self.exam_name_label.configure(background="#CED4DA")
        self.exam_name_label.configure(disabledforeground="#a3a3a3")
        self.exam_name_label.configure(foreground="#000000")
        self.exam_name_label.configure(highlightbackground="#d9d9d9")
        self.exam_name_label.configure(highlightcolor="black")
        self.exam_name_label.configure(text='''Exam name :''')

        self.exam_date_label = tk.Label(top)
        self.exam_date_label.place(relx=0.199, rely=0.348, height=21, width=74)
        self.exam_date_label.configure(activebackground="#f9f9f9")
        self.exam_date_label.configure(activeforeground="black")
        self.exam_date_label.configure(background="#CED4DA")
        self.exam_date_label.configure(disabledforeground="#a3a3a3")
        self.exam_date_label.configure(foreground="#000000")
        self.exam_date_label.configure(highlightbackground="#d9d9d9")
        self.exam_date_label.configure(highlightcolor="black")
        self.exam_date_label.configure(text='''Exam date :''')

        self.tot_marks_label = tk.Label(top)
        self.tot_marks_label.place(relx=0.175, rely=0.538, height=21, width=84)
        self.tot_marks_label.configure(activebackground="#f9f9f9")
        self.tot_marks_label.configure(activeforeground="black")
        self.tot_marks_label.configure(background="#CED4DA")
        self.tot_marks_label.configure(disabledforeground="#a3a3a3")
        self.tot_marks_label.configure(foreground="#000000")
        self.tot_marks_label.configure(highlightbackground="#d9d9d9")
        self.tot_marks_label.configure(highlightcolor="black")
        self.tot_marks_label.configure(text='''Total marks :''')

        self.sub_code_label = tk.Label(top)
        self.sub_code_label.place(relx=0.164, rely=0.728, height=21, width=84)
        self.sub_code_label.configure(activebackground="#f9f9f9")
        self.sub_code_label.configure(activeforeground="black")
        self.sub_code_label.configure(background="#CED4DA")
        self.sub_code_label.configure(disabledforeground="#a3a3a3")
        self.sub_code_label.configure(foreground="#000000")
        self.sub_code_label.configure(highlightbackground="#d9d9d9")
        self.sub_code_label.configure(highlightcolor="black")
        self.sub_code_label.configure(text='''Subject code :''')


root = tk.Tk()
top = ExamAdd (root)
root.mainloop()