import tkinter as tk


class ResultModify:
    def __init__(self, top=None):
        top.geometry("327x430+589+46")
        top.minsize(120, 1)
        top.maxsize(1370, 749)
        top.resizable(1,  1)
        top.title("Modify")
        top.configure(background="#CED4DA")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")

        self.Label1 = tk.Label(top)
        self.Label1.place(relx=0.245, rely=0.023, height=14, width=154)
        self.Label1.configure(activebackground="#CED4DA")
        self.Label1.configure(activeforeground="black")
        self.Label1.configure(background="#CED4DA")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(font="-family {Segoe UI} -size 13 -weight bold")
        self.Label1.configure(foreground="#212529")
        self.Label1.configure(highlightbackground="#d9d9d9")
        self.Label1.configure(highlightcolor="black")
        self.Label1.configure(text='''PRESENT DATA''')

        self.Label1_1 = tk.Label(top)
        self.Label1_1.place(relx=0.306, rely=0.465, height=14, width=114)
        self.Label1_1.configure(activebackground="#f9f9f9")
        self.Label1_1.configure(activeforeground="black")
        self.Label1_1.configure(background="#CED4DA")
        self.Label1_1.configure(disabledforeground="#a3a3a3")
        self.Label1_1.configure(font="-family {Segoe UI} -size 13 -weight bold")
        self.Label1_1.configure(foreground="#212529")
        self.Label1_1.configure(highlightbackground="#d9d9d9")
        self.Label1_1.configure(highlightcolor="black")
        self.Label1_1.configure(text='''NEW DATA''')

        self.marks_label1 = tk.Label(top)
        self.marks_label1.place(relx=0.125, rely=0.167, height=12, width=95)
        self.marks_label1.configure(activebackground="#f9f9f9")
        self.marks_label1.configure(activeforeground="black")
        self.marks_label1.configure(background="#CED4DA")
        self.marks_label1.configure(disabledforeground="#a3a3a3")
        self.marks_label1.configure(foreground="#000000")
        self.marks_label1.configure(highlightbackground="#d9d9d9")
        self.marks_label1.configure(highlightcolor="black")
        self.marks_label1.configure(text='''Marks obtained :''')

        self.res_label1 = tk.Label(top)
        self.res_label1.place(relx=0.275, rely=0.24, height=13, width=46)
        self.res_label1.configure(activebackground="#f9f9f9")
        self.res_label1.configure(activeforeground="black")
        self.res_label1.configure(background="#CED4DA")
        self.res_label1.configure(disabledforeground="#a3a3a3")
        self.res_label1.configure(foreground="#000000")
        self.res_label1.configure(highlightbackground="#d9d9d9")
        self.res_label1.configure(highlightcolor="black")
        self.res_label1.configure(text='''Result :''')

        self.res_id_label1 = tk.Label(top)
        self.res_id_label1.place(relx=0.245, rely=0.098, height=14, width=55)
        self.res_id_label1.configure(activebackground="#f9f9f9")
        self.res_id_label1.configure(activeforeground="black")
        self.res_id_label1.configure(background="#CED4DA")
        self.res_id_label1.configure(disabledforeground="#a3a3a3")
        self.res_id_label1.configure(foreground="#000000")
        self.res_id_label1.configure(highlightbackground="#d9d9d9")
        self.res_id_label1.configure(highlightcolor="black")
        self.res_id_label1.configure(text='''Result id :''')

        self.exam_id_label = tk.Label(top)
        self.exam_id_label.place(relx=0.239, rely=0.381, height=13, width=60)
        self.exam_id_label.configure(activebackground="#f9f9f9")
        self.exam_id_label.configure(activeforeground="black")
        self.exam_id_label.configure(background="#CED4DA")
        self.exam_id_label.configure(disabledforeground="#a3a3a3")
        self.exam_id_label.configure(foreground="#000000")
        self.exam_id_label.configure(highlightbackground="#d9d9d9")
        self.exam_id_label.configure(highlightcolor="black")
        self.exam_id_label.configure(text='''Exam id :''')

        self.student_id_label1 = tk.Label(top)
        self.student_id_label1.place(relx=0.214, rely=0.312, height=13, width=64)

        self.student_id_label1.configure(activebackground="#f9f9f9")
        self.student_id_label1.configure(activeforeground="black")
        self.student_id_label1.configure(background="#CED4DA")
        self.student_id_label1.configure(disabledforeground="#a3a3a3")
        self.student_id_label1.configure(foreground="#000000")
        self.student_id_label1.configure(highlightbackground="#d9d9d9")
        self.student_id_label1.configure(highlightcolor="black")
        self.student_id_label1.configure(text='''Student id :''')

        self.res_id_entry1 = tk.Entry(top)
        self.res_id_entry1.place(relx=0.459, rely=0.093, height=20
                , relwidth=0.318)
        self.res_id_entry1.configure(background="white")
        self.res_id_entry1.configure(disabledforeground="#a3a3a3")
        self.res_id_entry1.configure(font="TkFixedFont")
        self.res_id_entry1.configure(foreground="#000000")
        self.res_id_entry1.configure(highlightbackground="#d9d9d9")
        self.res_id_entry1.configure(highlightcolor="black")
        self.res_id_entry1.configure(insertbackground="black")
        self.res_id_entry1.configure(selectbackground="blue")
        self.res_id_entry1.configure(selectforeground="white")

        self.marks_entry1 = tk.Entry(top)
        self.marks_entry1.place(relx=0.459, rely=0.163, height=20
                , relwidth=0.318)
        self.marks_entry1.configure(background="white")
        self.marks_entry1.configure(disabledforeground="#a3a3a3")
        self.marks_entry1.configure(font="TkFixedFont")
        self.marks_entry1.configure(foreground="#000000")
        self.marks_entry1.configure(highlightbackground="#d9d9d9")
        self.marks_entry1.configure(highlightcolor="black")
        self.marks_entry1.configure(insertbackground="black")
        self.marks_entry1.configure(selectbackground="blue")
        self.marks_entry1.configure(selectforeground="white")

        self.res_entry1 = tk.Entry(top)
        self.res_entry1.place(relx=0.459, rely=0.233, height=20, relwidth=0.318)
        self.res_entry1.configure(background="white")
        self.res_entry1.configure(disabledforeground="#a3a3a3")
        self.res_entry1.configure(font="TkFixedFont")
        self.res_entry1.configure(foreground="#000000")
        self.res_entry1.configure(highlightbackground="#d9d9d9")
        self.res_entry1.configure(highlightcolor="black")
        self.res_entry1.configure(insertbackground="black")
        self.res_entry1.configure(selectbackground="blue")
        self.res_entry1.configure(selectforeground="white")

        self.student_id_entry1 = tk.Entry(top)
        self.student_id_entry1.place(relx=0.459, rely=0.302, height=20
                , relwidth=0.318)
        self.student_id_entry1.configure(background="white")
        self.student_id_entry1.configure(disabledforeground="#a3a3a3")
        self.student_id_entry1.configure(font="TkFixedFont")
        self.student_id_entry1.configure(foreground="#000000")
        self.student_id_entry1.configure(highlightbackground="#d9d9d9")
        self.student_id_entry1.configure(highlightcolor="black")
        self.student_id_entry1.configure(insertbackground="black")
        self.student_id_entry1.configure(selectbackground="blue")
        self.student_id_entry1.configure(selectforeground="white")

        self.exam_id_entry1 = tk.Entry(top)
        self.exam_id_entry1.place(relx=0.459, rely=0.372, height=20
                , relwidth=0.318)
        self.exam_id_entry1.configure(background="white")
        self.exam_id_entry1.configure(disabledforeground="#a3a3a3")
        self.exam_id_entry1.configure(font="TkFixedFont")
        self.exam_id_entry1.configure(foreground="#000000")
        self.exam_id_entry1.configure(highlightbackground="#d9d9d9")
        self.exam_id_entry1.configure(highlightcolor="black")
        self.exam_id_entry1.configure(insertbackground="black")
        self.exam_id_entry1.configure(selectbackground="blue")
        self.exam_id_entry1.configure(selectforeground="white")

        self.res_id_entry2 = tk.Entry(top)
        self.res_id_entry2.place(relx=0.459, rely=0.535, height=20
                , relwidth=0.318)
        self.res_id_entry2.configure(background="white")
        self.res_id_entry2.configure(disabledforeground="#a3a3a3")
        self.res_id_entry2.configure(font="TkFixedFont")
        self.res_id_entry2.configure(foreground="#000000")
        self.res_id_entry2.configure(highlightbackground="#d9d9d9")
        self.res_id_entry2.configure(highlightcolor="black")
        self.res_id_entry2.configure(insertbackground="black")
        self.res_id_entry2.configure(selectbackground="blue")
        self.res_id_entry2.configure(selectforeground="white")

        self.marks_entry2 = tk.Entry(top)
        self.marks_entry2.place(relx=0.459, rely=0.605, height=20
                , relwidth=0.318)
        self.marks_entry2.configure(background="white")
        self.marks_entry2.configure(disabledforeground="#a3a3a3")
        self.marks_entry2.configure(font="TkFixedFont")
        self.marks_entry2.configure(foreground="#000000")
        self.marks_entry2.configure(highlightbackground="#d9d9d9")
        self.marks_entry2.configure(highlightcolor="black")
        self.marks_entry2.configure(insertbackground="black")
        self.marks_entry2.configure(selectbackground="blue")
        self.marks_entry2.configure(selectforeground="white")

        self.res_entry2 = tk.Entry(top)
        self.res_entry2.place(relx=0.459, rely=0.674, height=20, relwidth=0.318)
        self.res_entry2.configure(background="white")
        self.res_entry2.configure(disabledforeground="#a3a3a3")
        self.res_entry2.configure(font="TkFixedFont")
        self.res_entry2.configure(foreground="#000000")
        self.res_entry2.configure(highlightbackground="#d9d9d9")
        self.res_entry2.configure(highlightcolor="black")
        self.res_entry2.configure(insertbackground="black")
        self.res_entry2.configure(selectbackground="blue")
        self.res_entry2.configure(selectforeground="white")

        self.student_id_entry2 = tk.Entry(top)
        self.student_id_entry2.place(relx=0.459, rely=0.744, height=20
                , relwidth=0.318)
        self.student_id_entry2.configure(background="white")
        self.student_id_entry2.configure(disabledforeground="#a3a3a3")
        self.student_id_entry2.configure(font="TkFixedFont")
        self.student_id_entry2.configure(foreground="#000000")
        self.student_id_entry2.configure(highlightbackground="#d9d9d9")
        self.student_id_entry2.configure(highlightcolor="black")
        self.student_id_entry2.configure(insertbackground="black")
        self.student_id_entry2.configure(selectbackground="blue")
        self.student_id_entry2.configure(selectforeground="white")

        self.exam_id_entry2 = tk.Entry(top)
        self.exam_id_entry2.place(relx=0.459, rely=0.814, height=20
                , relwidth=0.318)
        self.exam_id_entry2.configure(background="white")
        self.exam_id_entry2.configure(disabledforeground="#a3a3a3")
        self.exam_id_entry2.configure(font="TkFixedFont")
        self.exam_id_entry2.configure(foreground="#000000")
        self.exam_id_entry2.configure(highlightbackground="#d9d9d9")
        self.exam_id_entry2.configure(highlightcolor="black")
        self.exam_id_entry2.configure(insertbackground="black")
        self.exam_id_entry2.configure(selectbackground="blue")
        self.exam_id_entry2.configure(selectforeground="white")

        self.Entry1_7 = tk.Entry(top)
        self.Entry1_7.place(relx=2.875, rely=1.828, height=20, relwidth=0.318)
        self.Entry1_7.configure(background="white")
        self.Entry1_7.configure(disabledforeground="#a3a3a3")
        self.Entry1_7.configure(font="TkFixedFont")
        self.Entry1_7.configure(foreground="#000000")
        self.Entry1_7.configure(highlightbackground="#d9d9d9")
        self.Entry1_7.configure(highlightcolor="black")
        self.Entry1_7.configure(insertbackground="black")
        self.Entry1_7.configure(selectbackground="blue")
        self.Entry1_7.configure(selectforeground="white")

        self.res_id_label2 = tk.Label(top)
        self.res_id_label2.place(relx=0.245, rely=0.54, height=14, width=55)
        self.res_id_label2.configure(activebackground="#f9f9f9")
        self.res_id_label2.configure(activeforeground="black")
        self.res_id_label2.configure(background="#CED4DA")
        self.res_id_label2.configure(disabledforeground="#a3a3a3")
        self.res_id_label2.configure(foreground="#000000")
        self.res_id_label2.configure(highlightbackground="#d9d9d9")
        self.res_id_label2.configure(highlightcolor="black")
        self.res_id_label2.configure(text='''Result id :''')

        self.marks_label2 = tk.Label(top)
        self.marks_label2.place(relx=0.128, rely=0.609, height=13, width=96)
        self.marks_label2.configure(activebackground="#f9f9f9")
        self.marks_label2.configure(activeforeground="black")
        self.marks_label2.configure(background="#CED4DA")
        self.marks_label2.configure(disabledforeground="#a3a3a3")
        self.marks_label2.configure(foreground="#000000")
        self.marks_label2.configure(highlightbackground="#d9d9d9")
        self.marks_label2.configure(highlightcolor="black")
        self.marks_label2.configure(text='''Marks obtained :''')

        self.res_label2 = tk.Label(top)
        self.res_label2.place(relx=0.269, rely=0.681, height=12, width=55)
        self.res_label2.configure(activebackground="#f9f9f9")
        self.res_label2.configure(activeforeground="black")
        self.res_label2.configure(background="#CED4DA")
        self.res_label2.configure(disabledforeground="#a3a3a3")
        self.res_label2.configure(foreground="#000000")
        self.res_label2.configure(highlightbackground="#d9d9d9")
        self.res_label2.configure(highlightcolor="black")
        self.res_label2.configure(text='''Result :''')

        self.student_id_label2 = tk.Label(top)
        self.student_id_label2.place(relx=0.22, rely=0.753, height=13, width=64)
        self.student_id_label2.configure(activebackground="#f9f9f9")
        self.student_id_label2.configure(activeforeground="black")
        self.student_id_label2.configure(background="#CED4DA")
        self.student_id_label2.configure(disabledforeground="#a3a3a3")
        self.student_id_label2.configure(foreground="#000000")
        self.student_id_label2.configure(highlightbackground="#d9d9d9")
        self.student_id_label2.configure(highlightcolor="black")
        self.student_id_label2.configure(text='''Student id :''')

        self.exam_id_label2 = tk.Label(top)
        self.exam_id_label2.place(relx=0.226, rely=0.823, height=13, width=70)
        self.exam_id_label2.configure(activebackground="#f9f9f9")
        self.exam_id_label2.configure(activeforeground="black")
        self.exam_id_label2.configure(background="#CED4DA")
        self.exam_id_label2.configure(disabledforeground="#a3a3a3")
        self.exam_id_label2.configure(foreground="#000000")
        self.exam_id_label2.configure(highlightbackground="#d9d9d9")
        self.exam_id_label2.configure(highlightcolor="black")
        self.exam_id_label2.configure(text='''Exam id :''')

        self.modify_button = tk.Button(top)
        self.modify_button.place(relx=0.642, rely=0.907, height=24, width=77)
        self.modify_button.configure(activebackground="#ececec")
        self.modify_button.configure(activeforeground="#000000")
        self.modify_button.configure(background="#E9ECEF")
        self.modify_button.configure(disabledforeground="#a3a3a3")
        self.modify_button.configure(foreground="#000000")
        self.modify_button.configure(highlightbackground="#d9d9d9")
        self.modify_button.configure(highlightcolor="black")
        self.modify_button.configure(pady="0")
        self.modify_button.configure(text='''Modify''')

        self.cancel_button = tk.Button(top)
        self.cancel_button.place(relx=0.153, rely=0.907, height=24, width=77)
        self.cancel_button.configure(activebackground="#ececec")
        self.cancel_button.configure(activeforeground="#000000")
        self.cancel_button.configure(background="#E9ECEF")
        self.cancel_button.configure(disabledforeground="#a3a3a3")
        self.cancel_button.configure(foreground="#000000")
        self.cancel_button.configure(highlightbackground="#d9d9d9")
        self.cancel_button.configure(highlightcolor="black")
        self.cancel_button.configure(pady="0")
        self.cancel_button.configure(text='''Cancel''')


root = tk.Tk()
top = ResultModify (root)
root.mainloop()