import tkinter as tk


class SubjectModify:
    def __init__(self, top=None):
        top.geometry("327x370+455+152")
        top.minsize(120, 1)
        top.maxsize(1370, 749)
        top.resizable(0,0)
        top.title("Modify")
        top.configure(background="#CED4DA")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")

        self.Label1 = tk.Label(top)
        self.Label1.place(relx=0.245, rely=0.027, height=22, width=154)
        self.Label1.configure(activebackground="#CED4DA")
        self.Label1.configure(activeforeground="black")
        self.Label1.configure(background="#CED4DA")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(font="-family {Segoe UI} -size 13 -weight bold")
        self.Label1.configure(foreground="#212529")
        self.Label1.configure(highlightbackground="#d9d9d9")
        self.Label1.configure(highlightcolor="black")
        self.Label1.configure(text='''PRESENT DATA''')

        self.Label1_1 = tk.Label(top)
        self.Label1_1.place(relx=0.306, rely=0.432, height=22, width=114)
        self.Label1_1.configure(activebackground="#f9f9f9")
        self.Label1_1.configure(activeforeground="black")
        self.Label1_1.configure(background="#CED4DA")
        self.Label1_1.configure(disabledforeground="#a3a3a3")
        self.Label1_1.configure(font="-family {Segoe UI} -size 13 -weight bold")
        self.Label1_1.configure(foreground="#212529")
        self.Label1_1.configure(highlightbackground="#d9d9d9")
        self.Label1_1.configure(highlightcolor="black")
        self.Label1_1.configure(text='''NEW DATA''')

        self.name_label1 = tk.Label(top)
        self.name_label1.place(relx=0.122, rely=0.189, height=19, width=95)
        self.name_label1.configure(activebackground="#f9f9f9")
        self.name_label1.configure(activeforeground="black")
        self.name_label1.configure(background="#CED4DA")
        self.name_label1.configure(disabledforeground="#a3a3a3")
        self.name_label1.configure(foreground="#000000")
        self.name_label1.configure(highlightbackground="#d9d9d9")
        self.name_label1.configure(highlightcolor="black")
        self.name_label1.configure(text='''Subject name :''')

        self.credit_label1 = tk.Label(top)
        self.credit_label1.place(relx=0.135, rely=0.27, height=20, width=86)
        self.credit_label1.configure(activebackground="#f9f9f9")
        self.credit_label1.configure(activeforeground="black")
        self.credit_label1.configure(background="#CED4DA")
        self.credit_label1.configure(disabledforeground="#a3a3a3")
        self.credit_label1.configure(foreground="#000000")
        self.credit_label1.configure(highlightbackground="#d9d9d9")
        self.credit_label1.configure(highlightcolor="black")
        self.credit_label1.configure(text='''Subject credit :''')

        self.code_label1 = tk.Label(top)
        self.code_label1.place(relx=0.128, rely=0.103, height=22, width=95)
        self.code_label1.configure(activebackground="#f9f9f9")
        self.code_label1.configure(activeforeground="black")
        self.code_label1.configure(background="#CED4DA")
        self.code_label1.configure(disabledforeground="#a3a3a3")
        self.code_label1.configure(foreground="#000000")
        self.code_label1.configure(highlightbackground="#d9d9d9")
        self.code_label1.configure(highlightcolor="black")
        self.code_label1.configure(text='''Subject code :''')

        self.branch_id_label1 = tk.Label(top)
        self.branch_id_label1.place(relx=0.183, rely=0.362, height=11, width=74)
        self.branch_id_label1.configure(activebackground="#f9f9f9")
        self.branch_id_label1.configure(activeforeground="black")
        self.branch_id_label1.configure(background="#CED4DA")
        self.branch_id_label1.configure(disabledforeground="#a3a3a3")
        self.branch_id_label1.configure(foreground="#000000")
        self.branch_id_label1.configure(highlightbackground="#d9d9d9")
        self.branch_id_label1.configure(highlightcolor="black")
        self.branch_id_label1.configure(text='''Branch id :''')

        self.code_entry1 = tk.Entry(top)
        self.code_entry1.place(relx=0.459, rely=0.108, height=20, relwidth=0.318)

        self.code_entry1.configure(background="white")
        self.code_entry1.configure(disabledforeground="#a3a3a3")
        self.code_entry1.configure(font="TkFixedFont")
        self.code_entry1.configure(foreground="#000000")
        self.code_entry1.configure(highlightbackground="#d9d9d9")
        self.code_entry1.configure(highlightcolor="black")
        self.code_entry1.configure(insertbackground="black")
        self.code_entry1.configure(selectbackground="blue")
        self.code_entry1.configure(selectforeground="white")

        self.name_entry1 = tk.Entry(top)
        self.name_entry1.place(relx=0.459, rely=0.189, height=20, relwidth=0.318)

        self.name_entry1.configure(background="white")
        self.name_entry1.configure(disabledforeground="#a3a3a3")
        self.name_entry1.configure(font="TkFixedFont")
        self.name_entry1.configure(foreground="#000000")
        self.name_entry1.configure(highlightbackground="#d9d9d9")
        self.name_entry1.configure(highlightcolor="black")
        self.name_entry1.configure(insertbackground="black")
        self.name_entry1.configure(selectbackground="blue")
        self.name_entry1.configure(selectforeground="white")

        self.credit_entry1 = tk.Entry(top)
        self.credit_entry1.place(relx=0.459, rely=0.27, height=20
                , relwidth=0.318)
        self.credit_entry1.configure(background="white")
        self.credit_entry1.configure(disabledforeground="#a3a3a3")
        self.credit_entry1.configure(font="TkFixedFont")
        self.credit_entry1.configure(foreground="#000000")
        self.credit_entry1.configure(highlightbackground="#d9d9d9")
        self.credit_entry1.configure(highlightcolor="black")
        self.credit_entry1.configure(insertbackground="black")
        self.credit_entry1.configure(selectbackground="blue")
        self.credit_entry1.configure(selectforeground="white")

        self.branch_id_entry1 = tk.Entry(top)
        self.branch_id_entry1.place(relx=0.459, rely=0.351, height=20
                , relwidth=0.318)
        self.branch_id_entry1.configure(background="white")
        self.branch_id_entry1.configure(disabledforeground="#a3a3a3")
        self.branch_id_entry1.configure(font="TkFixedFont")
        self.branch_id_entry1.configure(foreground="#000000")
        self.branch_id_entry1.configure(highlightbackground="#d9d9d9")
        self.branch_id_entry1.configure(highlightcolor="black")
        self.branch_id_entry1.configure(insertbackground="black")
        self.branch_id_entry1.configure(selectbackground="blue")
        self.branch_id_entry1.configure(selectforeground="white")

        self.code_entry2 = tk.Entry(top)
        self.code_entry2.place(relx=0.459, rely=0.514, height=20, relwidth=0.318)

        self.code_entry2.configure(background="white")
        self.code_entry2.configure(disabledforeground="#a3a3a3")
        self.code_entry2.configure(font="TkFixedFont")
        self.code_entry2.configure(foreground="#000000")
        self.code_entry2.configure(highlightbackground="#d9d9d9")
        self.code_entry2.configure(highlightcolor="black")
        self.code_entry2.configure(insertbackground="black")
        self.code_entry2.configure(selectbackground="blue")
        self.code_entry2.configure(selectforeground="white")

        self.name_entry2 = tk.Entry(top)
        self.name_entry2.place(relx=0.459, rely=0.595, height=20, relwidth=0.318)

        self.name_entry2.configure(background="white")
        self.name_entry2.configure(disabledforeground="#a3a3a3")
        self.name_entry2.configure(font="TkFixedFont")
        self.name_entry2.configure(foreground="#000000")
        self.name_entry2.configure(highlightbackground="#d9d9d9")
        self.name_entry2.configure(highlightcolor="black")
        self.name_entry2.configure(insertbackground="black")
        self.name_entry2.configure(selectbackground="blue")
        self.name_entry2.configure(selectforeground="white")

        self.credit_entry2 = tk.Entry(top)
        self.credit_entry2.place(relx=0.459, rely=0.676, height=20
                , relwidth=0.318)
        self.credit_entry2.configure(background="white")
        self.credit_entry2.configure(disabledforeground="#a3a3a3")
        self.credit_entry2.configure(font="TkFixedFont")
        self.credit_entry2.configure(foreground="#000000")
        self.credit_entry2.configure(highlightbackground="#d9d9d9")
        self.credit_entry2.configure(highlightcolor="black")
        self.credit_entry2.configure(insertbackground="black")
        self.credit_entry2.configure(selectbackground="blue")
        self.credit_entry2.configure(selectforeground="white")

        self.branch_id_entry2 = tk.Entry(top)
        self.branch_id_entry2.place(relx=0.459, rely=0.757, height=20
                , relwidth=0.318)
        self.branch_id_entry2.configure(background="white")
        self.branch_id_entry2.configure(disabledforeground="#a3a3a3")
        self.branch_id_entry2.configure(font="TkFixedFont")
        self.branch_id_entry2.configure(foreground="#000000")
        self.branch_id_entry2.configure(highlightbackground="#d9d9d9")
        self.branch_id_entry2.configure(highlightcolor="black")
        self.branch_id_entry2.configure(insertbackground="black")
        self.branch_id_entry2.configure(selectbackground="blue")
        self.branch_id_entry2.configure(selectforeground="white")

        self.code_label2 = tk.Label(top)
        self.code_label2.place(relx=0.153, rely=0.514, height=22, width=85)
        self.code_label2.configure(activebackground="#f9f9f9")
        self.code_label2.configure(activeforeground="black")
        self.code_label2.configure(background="#CED4DA")
        self.code_label2.configure(disabledforeground="#a3a3a3")
        self.code_label2.configure(foreground="#000000")
        self.code_label2.configure(highlightbackground="#d9d9d9")
        self.code_label2.configure(highlightcolor="black")
        self.code_label2.configure(text='''Subject code :''')

        self.name_label2 = tk.Label(top)
        self.name_label2.place(relx=0.147, rely=0.595, height=20, width=86)
        self.name_label2.configure(activebackground="#f9f9f9")
        self.name_label2.configure(activeforeground="black")
        self.name_label2.configure(background="#CED4DA")
        self.name_label2.configure(disabledforeground="#a3a3a3")
        self.name_label2.configure(foreground="#000000")
        self.name_label2.configure(highlightbackground="#d9d9d9")
        self.name_label2.configure(highlightcolor="black")
        self.name_label2.configure(text='''Subject name :''')

        self.credit_label2 = tk.Label(top)
        self.credit_label2.place(relx=0.15, rely=0.673, height=19, width=85)
        self.credit_label2.configure(activebackground="#f9f9f9")
        self.credit_label2.configure(activeforeground="black")
        self.credit_label2.configure(background="#CED4DA")
        self.credit_label2.configure(disabledforeground="#a3a3a3")
        self.credit_label2.configure(foreground="#000000")
        self.credit_label2.configure(highlightbackground="#d9d9d9")
        self.credit_label2.configure(highlightcolor="black")
        self.credit_label2.configure(text='''Subject credit :''')

        self.branch_id_label2 = tk.Label(top)
        self.branch_id_label2.place(relx=0.214, rely=0.768, height=11, width=64)
        self.branch_id_label2.configure(activebackground="#f9f9f9")
        self.branch_id_label2.configure(activeforeground="black")
        self.branch_id_label2.configure(background="#CED4DA")
        self.branch_id_label2.configure(disabledforeground="#a3a3a3")
        self.branch_id_label2.configure(foreground="#000000")
        self.branch_id_label2.configure(highlightbackground="#d9d9d9")
        self.branch_id_label2.configure(highlightcolor="black")
        self.branch_id_label2.configure(text='''Branch id :''')

        self.modify_button = tk.Button(top)
        self.modify_button.place(relx=0.612, rely=0.865, height=24, width=77)
        self.modify_button.configure(activebackground="#ececec")
        self.modify_button.configure(activeforeground="#000000")
        self.modify_button.configure(background="#E9ECEF")
        self.modify_button.configure(disabledforeground="#a3a3a3")
        self.modify_button.configure(foreground="#000000")
        self.modify_button.configure(highlightbackground="#d9d9d9")
        self.modify_button.configure(highlightcolor="black")
        self.modify_button.configure(pady="0")
        self.modify_button.configure(text='''Modify''')

        self.cancel_button = tk.Button(top)
        self.cancel_button.place(relx=0.183, rely=0.865, height=24, width=77)
        self.cancel_button.configure(activebackground="#ececec")
        self.cancel_button.configure(activeforeground="#000000")
        self.cancel_button.configure(background="#E9ECEF")
        self.cancel_button.configure(disabledforeground="#a3a3a3")
        self.cancel_button.configure(foreground="#000000")
        self.cancel_button.configure(highlightbackground="#d9d9d9")
        self.cancel_button.configure(highlightcolor="black")
        self.cancel_button.configure(pady="0")
        self.cancel_button.configure(text='''Cancel''')


root = tk.Tk()
top = SubjectModify (root)
root.mainloop()