import tkinter as tk


class ResultAdd:
    def __init__(self, top=None):
        top.geometry("342x224+501+160")
        top.minsize(120, 1)
        top.maxsize(1370, 749)
        top.resizable(0,0)
        top.title("Add")
        top.configure(background="#CED4DA")
        top.configure(highlightcolor="black")

        self.res_id_label = tk.Label(top)
        self.res_id_label.place(relx=0.234, rely=0.089, height=15, width=64)
        self.res_id_label.configure(activebackground="#f9f9f9")
        self.res_id_label.configure(activeforeground="black")
        self.res_id_label.configure(background="#CED4DA")
        self.res_id_label.configure(disabledforeground="#a3a3a3")
        self.res_id_label.configure(foreground="#000000")
        self.res_id_label.configure(highlightbackground="#d9d9d9")
        self.res_id_label.configure(highlightcolor="black")
        self.res_id_label.configure(text='''Result id :''')

        self.marks_label = tk.Label(top)
        self.marks_label.place(relx=0.117, rely=0.223, height=19, width=104)
        self.marks_label.configure(activebackground="#f9f9f9")
        self.marks_label.configure(activeforeground="black")
        self.marks_label.configure(background="#CED4DA")
        self.marks_label.configure(disabledforeground="#a3a3a3")
        self.marks_label.configure(foreground="#000000")
        self.marks_label.configure(highlightbackground="#d9d9d9")
        self.marks_label.configure(highlightcolor="black")
        self.marks_label.configure(text='''Marks obtained :''')

        self.res_id_entry = tk.Entry(top)
        self.res_id_entry.place(relx=0.468, rely=0.089, height=20
                , relwidth=0.304)
        self.res_id_entry.configure(background="white")
        self.res_id_entry.configure(disabledforeground="#a3a3a3")
        self.res_id_entry.configure(font="TkFixedFont")
        self.res_id_entry.configure(foreground="#000000")
        self.res_id_entry.configure(highlightbackground="#d9d9d9")
        self.res_id_entry.configure(highlightcolor="black")
        self.res_id_entry.configure(insertbackground="black")
        self.res_id_entry.configure(selectbackground="blue")
        self.res_id_entry.configure(selectforeground="white")

        self.marks_entry = tk.Entry(top)
        self.marks_entry.place(relx=0.468, rely=0.223, height=20, relwidth=0.304)

        self.marks_entry.configure(background="white")
        self.marks_entry.configure(disabledforeground="#a3a3a3")
        self.marks_entry.configure(font="TkFixedFont")
        self.marks_entry.configure(foreground="#000000")
        self.marks_entry.configure(highlightbackground="#d9d9d9")
        self.marks_entry.configure(highlightcolor="black")
        self.marks_entry.configure(insertbackground="black")
        self.marks_entry.configure(selectbackground="blue")
        self.marks_entry.configure(selectforeground="white")

        self.back_button = tk.Button(top)
        self.back_button.place(relx=0.175, rely=0.804, height=24, width=87)
        self.back_button.configure(activebackground="#ececec")
        self.back_button.configure(activeforeground="#000000")
        self.back_button.configure(background="#E9ECEF")
        self.back_button.configure(disabledforeground="#a3a3a3")
        self.back_button.configure(foreground="#000000")
        self.back_button.configure(highlightbackground="#d9d9d9")
        self.back_button.configure(highlightcolor="black")
        self.back_button.configure(pady="0")
        self.back_button.configure(text='''Back''')

        self.add_button = tk.Button(top)
        self.add_button.place(relx=0.585, rely=0.804, height=24, width=87)
        self.add_button.configure(activebackground="#ececec")
        self.add_button.configure(activeforeground="#000000")
        self.add_button.configure(background="#E9ECEF")
        self.add_button.configure(disabledforeground="#a3a3a3")
        self.add_button.configure(foreground="#000000")
        self.add_button.configure(highlightbackground="#d9d9d9")
        self.add_button.configure(highlightcolor="black")
        self.add_button.configure(pady="0")
        self.add_button.configure(text='''Add''')

        self.res_label = tk.Label(top)
        self.res_label.place(relx=0.263, rely=0.357, height=19, width=54)
        self.res_label.configure(activebackground="#f9f9f9")
        self.res_label.configure(activeforeground="black")
        self.res_label.configure(background="#CED4DA")
        self.res_label.configure(disabledforeground="#a3a3a3")
        self.res_label.configure(foreground="#000000")
        self.res_label.configure(highlightbackground="#d9d9d9")
        self.res_label.configure(highlightcolor="black")
        self.res_label.configure(text='''Result :''')

        self.student_id_label = tk.Label(top)
        self.student_id_label.place(relx=0.205, rely=0.491, height=19, width=74)
        self.student_id_label.configure(activebackground="#f9f9f9")
        self.student_id_label.configure(activeforeground="black")
        self.student_id_label.configure(background="#CED4DA")
        self.student_id_label.configure(disabledforeground="#a3a3a3")
        self.student_id_label.configure(foreground="#000000")
        self.student_id_label.configure(highlightbackground="#d9d9d9")
        self.student_id_label.configure(highlightcolor="black")
        self.student_id_label.configure(text='''Student id :''')

        self.exam_id_label = tk.Label(top)
        self.exam_id_label.place(relx=0.219, rely=0.625, height=21, width=74)
        self.exam_id_label.configure(activebackground="#f9f9f9")
        self.exam_id_label.configure(activeforeground="black")
        self.exam_id_label.configure(background="#CED4DA")
        self.exam_id_label.configure(disabledforeground="#a3a3a3")
        self.exam_id_label.configure(foreground="#000000")
        self.exam_id_label.configure(highlightbackground="#d9d9d9")
        self.exam_id_label.configure(highlightcolor="black")
        self.exam_id_label.configure(text='''Exam id :''')

        self.res_entry = tk.Entry(top)
        self.res_entry.place(relx=0.468, rely=0.357, height=20, relwidth=0.304)
        self.res_entry.configure(background="white")
        self.res_entry.configure(disabledforeground="#a3a3a3")
        self.res_entry.configure(font="TkFixedFont")
        self.res_entry.configure(foreground="#000000")
        self.res_entry.configure(highlightbackground="#d9d9d9")
        self.res_entry.configure(highlightcolor="black")
        self.res_entry.configure(insertbackground="black")
        self.res_entry.configure(selectbackground="blue")
        self.res_entry.configure(selectforeground="white")

        self.student_id_entry = tk.Entry(top)
        self.student_id_entry.place(relx=0.468, rely=0.491, height=20
                , relwidth=0.304)
        self.student_id_entry.configure(background="white")
        self.student_id_entry.configure(disabledforeground="#a3a3a3")
        self.student_id_entry.configure(font="TkFixedFont")
        self.student_id_entry.configure(foreground="#000000")
        self.student_id_entry.configure(highlightbackground="#d9d9d9")
        self.student_id_entry.configure(highlightcolor="black")
        self.student_id_entry.configure(insertbackground="black")
        self.student_id_entry.configure(selectbackground="blue")
        self.student_id_entry.configure(selectforeground="white")

        self.exam_id_entry = tk.Entry(top)
        self.exam_id_entry.place(relx=0.468, rely=0.625, height=20
                , relwidth=0.304)
        self.exam_id_entry.configure(background="white")
        self.exam_id_entry.configure(disabledforeground="#a3a3a3")
        self.exam_id_entry.configure(font="TkFixedFont")
        self.exam_id_entry.configure(foreground="#000000")
        self.exam_id_entry.configure(highlightbackground="#d9d9d9")
        self.exam_id_entry.configure(highlightcolor="black")
        self.exam_id_entry.configure(insertbackground="black")
        self.exam_id_entry.configure(selectbackground="blue")
        self.exam_id_entry.configure(selectforeground="white")


root = tk.Tk()
top = ResultAdd (root)
root.mainloop()