import tkinter as tk


class StudentAdd:
    def __init__(self, top=None):

        top.geometry("342x224+510+158")
        top.minsize(120, 1)
        top.maxsize(1370, 749)
        top.resizable(0,0)
        top.title("Add")
        top.configure(background="#CED4DA")

        self.student_id_label = tk.Label(top)
        self.student_id_label.place(relx=0.211, rely=0.089, height=15, width=74)
        self.student_id_label.configure(activebackground="#f9f9f9")
        self.student_id_label.configure(activeforeground="black")
        self.student_id_label.configure(background="#CED4DA")
        self.student_id_label.configure(disabledforeground="#a3a3a3")
        self.student_id_label.configure(foreground="#000000")
        self.student_id_label.configure(highlightbackground="#d9d9d9")
        self.student_id_label.configure(highlightcolor="black")
        self.student_id_label.configure(text='''Student id :''')

        self.roll_no_label = tk.Label(top)
        self.roll_no_label.place(relx=0.257, rely=0.223, height=19, width=54)
        self.roll_no_label.configure(background="#CED4DA")
        self.roll_no_label.configure(disabledforeground="#a3a3a3")
        self.roll_no_label.configure(foreground="#000000")
        self.roll_no_label.configure(text='''Roll no. :''')

        self.student_id_entry = tk.Entry(top)
        self.student_id_entry.place(relx=0.468, rely=0.089, height=20
                , relwidth=0.304)
        self.student_id_entry.configure(background="white")
        self.student_id_entry.configure(foreground="#000000")
        self.student_id_entry.configure(highlightbackground="#d9d9d9")
        self.student_id_entry.configure(highlightcolor="black")
        self.student_id_entry.configure(insertbackground="black")
        self.student_id_entry.configure(selectbackground="blue")
        self.student_id_entry.configure(selectforeground="white")

        self.roll_no_entry = tk.Entry(top)
        self.roll_no_entry.place(relx=0.468, rely=0.223, height=20
                , relwidth=0.304)
        self.roll_no_entry.configure(background="white")
        self.roll_no_entry.configure(disabledforeground="#a3a3a3")
        self.roll_no_entry.configure(font="TkFixedFont")
        self.roll_no_entry.configure(foreground="#000000")
        self.roll_no_entry.configure(highlightbackground="#d9d9d9")
        self.roll_no_entry.configure(highlightcolor="black")
        self.roll_no_entry.configure(insertbackground="black")
        self.roll_no_entry.configure(selectbackground="blue")
        self.roll_no_entry.configure(selectforeground="white")

        self.back_button = tk.Button(top)
        self.back_button.place(relx=0.175, rely=0.804, height=24, width=87)
        self.back_button.configure(activebackground="#ececec")
        self.back_button.configure(activeforeground="#000000")
        self.back_button.configure(background="#E9ECEF")
        self.back_button.configure(disabledforeground="#a3a3a3")
        self.back_button.configure(foreground="#000000")
        self.back_button.configure(highlightbackground="#d9d9d9")
        self.back_button.configure(highlightcolor="black")
        self.back_button.configure(pady="0")
        self.back_button.configure(text='''Back''')

        self.add_button = tk.Button(top)
        self.add_button.place(relx=0.585, rely=0.804, height=24, width=87)
        self.add_button.configure(activebackground="#ececec")
        self.add_button.configure(activeforeground="#000000")
        self.add_button.configure(background="#E9ECEF")
        self.add_button.configure(disabledforeground="#a3a3a3")
        self.add_button.configure(foreground="#000000")
        self.add_button.configure(highlightbackground="#d9d9d9")
        self.add_button.configure(highlightcolor="black")
        self.add_button.configure(pady="0")
        self.add_button.configure(text='''Add''')

        self.email_label = tk.Label(top)
        self.email_label.place(relx=0.254, rely=0.357, height=19, width=64)
        self.email_label.configure(activebackground="#f9f9f9")
        self.email_label.configure(activeforeground="black")
        self.email_label.configure(background="#CED4DA")
        self.email_label.configure(disabledforeground="#a3a3a3")
        self.email_label.configure(foreground="#000000")
        self.email_label.configure(highlightbackground="#d9d9d9")
        self.email_label.configure(highlightcolor="black")
        self.email_label.configure(text='''E-mail :''')

        self.password_label = tk.Label(top)
        self.password_label.place(relx=0.234, rely=0.491, height=19, width=64)
        self.password_label.configure(activebackground="#f9f9f9")
        self.password_label.configure(activeforeground="black")
        self.password_label.configure(background="#CED4DA")
        self.password_label.configure(cursor="fleur")
        self.password_label.configure(disabledforeground="#a3a3a3")
        self.password_label.configure(foreground="#000000")
        self.password_label.configure(highlightbackground="#d9d9d9")
        self.password_label.configure(highlightcolor="black")
        self.password_label.configure(text='''Password :''')

        self.branch_id_label = tk.Label(top)
        self.branch_id_label.place(relx=0.219, rely=0.625, height=21, width=74)
        self.branch_id_label.configure(activebackground="#f9f9f9")
        self.branch_id_label.configure(activeforeground="black")
        self.branch_id_label.configure(background="#CED4DA")
        self.branch_id_label.configure(disabledforeground="#a3a3a3")
        self.branch_id_label.configure(foreground="#000000")
        self.branch_id_label.configure(highlightbackground="#d9d9d9")
        self.branch_id_label.configure(highlightcolor="black")
        self.branch_id_label.configure(text='''Branch id :''')

        self.email_entry = tk.Entry(top)
        self.email_entry.place(relx=0.468, rely=0.357, height=20, relwidth=0.304)

        self.email_entry.configure(background="white")
        self.email_entry.configure(disabledforeground="#a3a3a3")
        self.email_entry.configure(font="TkFixedFont")
        self.email_entry.configure(foreground="#000000")
        self.email_entry.configure(highlightbackground="#d9d9d9")
        self.email_entry.configure(highlightcolor="black")
        self.email_entry.configure(insertbackground="black")
        self.email_entry.configure(selectbackground="blue")
        self.email_entry.configure(selectforeground="white")

        self.password_entry = tk.Entry(top)
        self.password_entry.place(relx=0.468, rely=0.491, height=20
                , relwidth=0.304)
        self.password_entry.configure(background="white")
        self.password_entry.configure(disabledforeground="#a3a3a3")
        self.password_entry.configure(font="TkFixedFont")
        self.password_entry.configure(foreground="#000000")
        self.password_entry.configure(highlightbackground="#d9d9d9")
        self.password_entry.configure(highlightcolor="black")
        self.password_entry.configure(insertbackground="black")
        self.password_entry.configure(selectbackground="blue")
        self.password_entry.configure(selectforeground="white")

        self.branch_id_entry = tk.Entry(top)
        self.branch_id_entry.place(relx=0.468, rely=0.625, height=20
                , relwidth=0.304)
        self.branch_id_entry.configure(background="white")
        self.branch_id_entry.configure(disabledforeground="#a3a3a3")
        self.branch_id_entry.configure(font="TkFixedFont")
        self.branch_id_entry.configure(foreground="#000000")
        self.branch_id_entry.configure(highlightbackground="#d9d9d9")
        self.branch_id_entry.configure(highlightcolor="black")
        self.branch_id_entry.configure(insertbackground="black")
        self.branch_id_entry.configure(selectbackground="blue")
        self.branch_id_entry.configure(selectforeground="white")


root = tk.Tk()
top = StudentAdd (root)
root.mainloop()